src/Dispatcher.js

Dispatcher/Context/StoreGroup/Store/UseCase can listen more than 10 events
This pull request supresss following warning
> (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

fix(dispatcher): supress memory leak warning of EventEmitter

---

src/Dispatcher.js
test/Dispatcher-test.js

Allow to use any type data to `payload.type`.
You can write following now!
```js
const dispatcher = new Dispatcher();
const expectedPayload = {
type: { /* string Symbol anything */ }
};
dispatcher.onDispatch(payload => {
assert.deepEqual(payload, expectedPayload);
done();
});
dispatcher.dispatch(expectedPayload);
```

fix(dispatcher): drop `payload.type` limitation

---

example/svg-feeling/src/js/store/AppStoreGroup.js
package.json
perf/node-memory-leak-testing/QueuedStoreGroup-memory-test.js
perf/node-memory-leak-testing/StoreGroup-memory-test.js
perf/node-memory-leak-testing/package.json
src/Context.js
src/UILayer/QueuedStoreGroup.js
src/UseCaseContext.js
src/UseCaseExecutor.js
src/index.js
test/QueuedStoreGroup-test.js
test/StoreGroup-test.js
test/UseCaseExecutor-test.js

It work as Sync/Async store group.
This commit include some changes:
- When UseCase's result is not promise, call immediately `didExecute`
- UseCaseExecutor  has `parentUseCase`
- Root UseCaseExecutor has not `parentUseCase`
- It similar with prototype chain(`Object.getPrototypeOf(Object.prototype); //=> null`)
- QueuedStoreGroup not dependant on async function like `setTimeout`.
- QueuedStoreGroup work as Sync or Async.
- QueuedStoreGroup dependant on execution of UseCase.
- StoreGroup focus on changing of store-self.
- QueuedStoreGroup focus on execution of UseCase.
```
{ signal: [
['Store',
{ name: "A",
wave: '0...3..0....', data:["Change"]},
{ name: "B",
wave: '0....3..0...', data:["Change"]},
],
{},
{
name: "UseCase",
wave: "0.20.......30.....", data:["will", "did"]
},
{ name: …
```

feat(StoreGroup): Add QueuedStoreGroup

---

src/Context.js
src/UILayer/QueuedStoreGroup.js
src/UILayer/StoreGroupValidator.js
test/QueuedStoreGroup-test.js

Currently, QueuedStoreGroup should not call `QueuedStoreGroup#emitChange()` when UseCase#dispatch is called.
#40 support only `didExecutedUseCase` events.
It is unexpected behavior for user.
We should support `UseCase#dispatch` events.
QueuedStoreGroup check changed stores and `QueuedStoreGroup#emitChange()` on following case:
- when emit root `didExecutedUseCase` events
- when emit every `didExecutedUseCase` events if `{ asap : true}` option is enabled
- when emit `UseCase#dispatch` events
- every `type`

QueuedStoreGroup should call #onChange when UseCase#dispatch is called

---

src/UILayer/QueuedStoreGroup.js
src/UILayer/StoreGroup.js
test/QueuedStoreGroup-test.js

- QueuedStoreGroup has not cache state.
- Cache is very buggy in StoreGroup
- Because QueuedStoreGroup reaction to events of UseCase instead of changes of store.
- Cache system should be in your Store.

fix(QueuedStoreGroup): remove state cache from QueuedStoreGroup

---

package.json
src/Context.js
src/UILayer/QueuedStoreGroup.js
src/UseCaseExecutor.js
test/QueuedStoreGroup-test.js
test/UseCaseExecutor-test.js

- Separate `didExecuted` into "didExecuted" and "complete".
- "didExecuted" event always is called **sync**
- "complete" event always is called **async**
For improving stability.
The timing of dispatching "didExecuted" event is **sync** or **async**.
It is affected by _UseCase implementation_.
In the pull request,  We add "complete" event and defined the behavior to following.
- "didExecuted" event always is called **sync**
- "complete" event always is called **async**
```js
context.useCase(useCaseA).execute();
```
1. **will execute** useCaseA
2. **did execute** useCaseA
3. if useCaseA reutrn `promise`
- when the `promise` is resolved, **complete** useCaseA
- when the `promise` is rejected, **complete** useCaseA
4. if useCaseA is not return any value
- **complete** useCaseA
The subscriber …

Breaking Change: add Context#onCompleteExecuteEachUseCase

---

example/counter/src/component/Counter.js
package.json
src/Dispatcher.js
src/Store.js
src/UILayer/QueuedStoreGroup.js
src/UILayer/StoreGroup.js
src/UseCase.js
src/UseCaseContext.js
src/UseCaseExecutor.js

[lru-map-like](https://github.com/azu/lru-map-like) is tiny implementation of LRU cache.
```
❯ package-size-analyzer -e lib/index.js
__ROOT__: 117.47 KB
<self>: 54.36 KB
assert: 11.43 KB
<self>: 11.43 KB
util: 15.4 KB
<self>: 15.4 KB
package-size-analyzer: 5.17 KB
<self>: 0 B
process: 5.17 KB
<self>: 5.17 KB
inherits: 672 B
<self>: 672 B
events: 8 KB
<self>: 8 KB
object-assign: 1.95 KB
<self>: 1.95 KB
lru-cache: 10.85 KB
<self>: 10.85 KB
pseudomap: 2.65 KB
<self>: 2.65 KB
yallist: 6.99 KB
<self>: 6.99 KB
```
minify and gzip
```
❯ bundle-size ./lib/index.js -e development -e production
./lib/index.js
env          bundle  minify   gzip
--           123 kB  68.7 kB  19.6 kB
development  123 kB  68.7 kB  19.6 kB
production   123 kB  68.7 kB  19.6 kB
```
```
❯ package-size-analyzer -e …
```

perf(StoreGroup): use lru-map-like insteadof lru-cache

---

src/Context.ts
src/Store.ts
src/StoreLike.ts
src/UILayer/QueuedStoreGroup.ts
src/UILayer/StoreGroup.ts

Motivation
----------
This introduce `StoreLike` interface to reduce `any` type from `Context.ts`.
Detailed Design
---------------
1. Introduce `StoreLike` interface which express that this objectjust
behave as a "Store" object.
2. `Store`, `StoreGroup` and `QueuedStoreGroup` implements `StoreLike`.
Remained Tasks
--------------
- I did above steps conservatively. So we might have more chances to
modify some signatures to use `StoreLike` instead of an actual classes ( https://github.com/almin/almin/issues/81 )

Introduce StoreLike interface

---

.babelrc
package.json

- Fix https://github.com/almin/almin/issues/82
- This leaves `.babelrc` for https://github.com/almin/almin/issues/83

Remove babel-preset-jsdoc-to-assert from unit test

---

src/Store.ts
src/payload/CompletedPayload.ts
src/payload/DidExecutedPayload.ts
src/payload/ErrorPayload.ts
src/payload/WillExecutedPayload.ts
test/UseCase-test.js

- Breaking Change
- Fix https://github.com/almin/almin/issues/86
- To detect the type of `***Payload`, you should use `is***Payload()`.

Remove ***Payload.Type static property

---

package.json

- __I don't think this is a breaking change because we have not published TypeScript version yet__.
- I open this to aim to upgrade our baseline version because upgrading TypeScript would be a breaking change. Semantic versioning is the care of this problem and I think it's better to iterate its cycle rapidly.  But I (we?) would not like to upgrade it if there is no need.

Upgrade TypeScript 2.2

---

example/todomvc-flow/.flowconfig
example/todomvc-flow/src/AppLocator.js
package.json
type-definitions/index.js.flow

todomvc-flow is not read flow type-def from almin.
```js
// @flow
"use strict";
import {UseCase} from 'almin';
UseCase.hogehoge; // UseCase is `unkown`
```
```
$ flow type-at-pos sample.js 4 1
(unknown)
/path/to/almin/example/todomvc-flow/sample.js:4:1,4:7
See the following locations:
/path/to/almin/example/todomvc-flow/sample.js:4:1-7:
any
```
https://flowtype.org/docs/declarations.html#declaration-files
`".js.flow” style. ` is better when distributing type-def.

fixes flow type-def can not be read.

---

package.json
src/UILayer/QueuedStoreGroup.ts
src/UILayer/StoreGroup.ts
src/UILayer/object-assign.d.ts
src/UILayer/object-assign.js
tsconfig.json

- enable `allowSyntheticDefaultImports`  for loading `@types/object-assign`
- remove "build:src:cp_obj" task. it is no more needed.
fix #89

fix(TypeScript): use @types/object-assign instead of object-assign.d.ts

---

docs/warnings/usecase-is-already-released.md
package.json
src/UseCaseExecutor.ts
src/UseCaseInstanceMap.ts
test/QueuedStoreGroup-test.js
test/UseCase-test.js

Following case is violation of UseCase lifecycle.
Almin don't support this pattern.
```
P: Parent UseCase
C: Child UseCase
P fin.   C fin.
|---------------|          |
P    |                     |
C---------------------|
```
Example:
```js
class ChildUseCase extends UseCase {}
class ParentUseCase extends UseCase {
execute() {
setTimeout(() => {
// isolate execution
this.context.useCase(new ChildUseCase()).execute().then(() => {
// ChildUseCase's dispatch is not work!
});
}, 100);
return Promise.resolve();
}
}
```
However, Almin should display warning message.
We want to add warning message to this case.
Edit:
See https://almin.js.org/docs/warnings/usecase-is-already-released.html for more details.
- Add `UseCaseInstanceMap` for managing instance of each UseCase.
- Similar with …

feat(UseCase): add warning message "UseCase is already released"

---

src/UseCaseContext.ts

`UseCaseContext._dispatcher` should be `UseCase | null`.
No `Dispatcher` type.
fix #123

fix(UseCaseContext): fix `_dispatcher` typing

---

src/UILayer/StoreGroup.ts

fix(StoreGroup): rename `get store()` to `get stores()`

---

src/Store.ts
src/StoreLike.ts
src/UILayer/QueuedStoreGroup.ts
src/UILayer/StoreGroup.ts
test/CQRSStoreGroup-test.js

Continute to `feat(Store): add Store#receivePayload(payload: Payload)` #160
- Remove the `prevState` argument of `Store#getState(prevState)`
We have introduced `Store#receivePayload(payload)` in #160 
This method aim to separate  **write in read** and **read in read**.
It is mixed context in a single method.
`Store#getState(prevState)` make us confuse.
The user could implement write and read using `getState(prevState)`.
```js
const initialState = 0;
class MyStore extends Store {
getState(prevState = initialState){
return prevState + 1;
}
}
```
We can implement this instadof the above mixed context implementation.
```ts
class Reactor extends Store {
receivePayload() {
const newState = this.reduce(this.state);
if (this.shouldStateUpdate(this.state, newState)) {
this.state = newState;
}
} …
```

Breaking Change: remove the arguments of Store#getState

---

src/Context.ts
src/Store.ts
src/StoreLike.ts
src/UILayer/CQRSStoreGroup.ts
src/UILayer/QueuedStoreGroup.ts
src/UILayer/StoreGroup.ts
src/UILayer/StoreGroupValidator.ts
test/typescript/almin-loading-test.ts
test/typescript/almin-test.ts

`Store` return a `State`
```ts
class Store<State> { 
state?: State;
getState(): State;
}
```
fix #163

chore(Store): Make clear the relation Store and State

---

src/Context.ts
src/Store.ts
src/StoreLike.ts
src/UILayer/CQRSStoreGroup.ts
src/UILayer/QueuedStoreGroup.ts
src/UILayer/StoreGroup.ts
src/UILayer/StoreGroupType.ts
src/UILayer/StoreGroupValidator.ts
src/index.ts
test/typescript/almin-test.ts

Follow up #165 #163 
**Edit(2017-04-20)**: Change the title to "Make Context#getState explicit"
This PR make `Context#getState` more type safe.
```ts
const storeGroup = new CQRSStoreGroup({
aState: new AStore(),
bState: new BStore()
});
// Context
const context = new Context({
dispatcher,
store: storeGroup
});
const state = context.getState();
console.log(state.aState.a);
console.log(state.bState.b);
```
Thanks to @kimamula !
----
<del>
I want to add `MapStoreToState` utility function for TypeScript.
It not have actual implementation, but it is a function...
We want to improve this as possible.
```ts
const mapping = {
A: new AStore(),
B: new BStore()
};
// Type hacking
const _StoreState = MapStoreToState(mapping);
type StoreState = typeof _StoreState;
const storeGroup = new …
```

feat(TypeScript): Make Context#getState explicit

---

src/UILayer/StoreGroupTypes.ts

Add `StoreToState` function.
This allow to get type of state without `StoreGroup#getState`.

feat(TypeScript): add `StoreToState` utility type converter

---

packages/almin/src/UILayer/StoreGroup.ts
packages/almin/yarn.lock
perf/benchmark/almin-0.9.js
perf/benchmark/almin-current.js
perf/benchmark/index.js
perf/benchmark/package.json
perf/benchmark/src/lots-of-stores-task.js
perf/benchmark/src/task.js

fix  #175
Number of stores : 500
```shell-session
$ node ./perf/benchmark/src/lots-of-stores-task.js
UseCase will -> did: 15ms
UseCase will -> complete: 21ms
Token Update State time: 14ms
```
I think that One StoreGroup has up to 500 stores.
500> stores should be separated StoreGroup.

perf(almin): add scalable stores perf test

---

packages/almin/src/FunctionalUseCase.ts
packages/almin/src/UILayer/StoreGroup.ts
packages/almin/src/UseCaseExecutor.ts
packages/almin/test/FunctionalUseCase-test.js
packages/almin/test/StoreGroup-test.js
packages/almin/test/UseCase-test.js

fix warning style
use `console.error`  for stack trace
- https://github.com/facebook/react/issues/4216
- https://github.com/BerkeleyTrue/warning
- https://github.com/facebook/fbjs/pull/183

fix(almin): fix warning message format

---

packages/almin/src/Context.ts
packages/almin/src/UseCaseContext.ts
packages/almin/src/UseCaseExecutor.ts
packages/almin/src/UseCaseInstanceMap.ts
packages/almin/test/UseCaseExecutor-test.js
packages/almin/test/typescript/almin-test.ts
packages/almin/test/use-case/CallableUseCase.js
packages/almin/test/use-case/ThrowUseCase.js
perf/benchmark/almin-0.12.js
perf/benchmark/index.js
perf/benchmark/pacakges/almin-0.12/index.js
perf/benchmark/pacakges/almin-0.12/package.json
perf/benchmark/package.json
perf/benchmark/src/index.js
perf/benchmark/yarn.lock

Fluent style UseCase https://github.com/almin/almin/issues/193
- Make exist `execute()` catchable(try-catch) that use `executor` method.
- `executor` method always catch sync error and async error(promise).

feat(UseCase): Fluent style UseCase

---

packages/almin-react-container/src/almin-react-container.tsx

```ts
const AppWrapContainer = AlminReactContainer.create<AppStoreGroupState>(AppContainer, context);
// AppWrapContainer's props {} | void
ReactDOM.render(<AppWrapContainer />, document.getElementById("js-app"));
````

fix(react-container): fix returned component props types

---

packages/almin/type-definitions/index.js.flow

I used almin with flowtype.  
Flowtype error occured in Context#constructor and StoreGroup#constructor.
[source/javascripts/main.js:11](https://github.com/Leko/WEB-EGG/tree/master/source/javascripts/main.js#L11)
```
v
11: const appContext = new Context({
12:   dispatcher,
13:   store: AppStoreGroup.create()
14: })
^ unused function argument
v-----------------------------
38: declare export class Context {
39:     getState(): mixed;
40:     onChange(onChangeHandler: (changingStores: Array<Store>) => mixed): Function;
...:
48: }
^ default constructor expects no arguments. See: node_modules/almin/lib/index.js.flow:38
```
---
[source/javascripts/store/AppStoreGroup.js:8](https://github.com/Leko/WEB-EGG/tree/master/source/javascripts/store/AppStoreGroup.js#L8)
```
v
8:     return new …
```

Fix 'unused function argument' in StoreGroup, Context

---

packages/almin/.zuul.yml

BREAKING CHANGE: Drop IE9/IE10 support
close #168

test(almin): Remove IE9/IE10 from E2E Tests

---

packages/almin/src/Context.ts
packages/almin/src/LifeCycleEventHub.ts
packages/almin/test/Context-test.js

LifeCycleEventHub does handler life cycle event insteadof Context.
Illusration:

refactor(almin): introduce LifeCycleEventHub

---

.textlintrc
examples/shopping-cart/README.md
examples/shopping-cart/package.json
examples/shopping-cart/src/index.js
examples/shopping-cart/webpack.server.config.js
packages/almin-logger/README.md
packages/almin-logger/package.json
packages/almin-logger/src/AsyncLogger.js
packages/almin-logger/src/SyncLogger.js
packages/almin-logger/src/log/LogGroup.js
packages/almin-logger/src/log/PrintLogger.js
packages/almin-logger/test/AsyncLogger-test.js
packages/almin-logger/test/SyncLogger-test.js
packages/almin-logger/test/store/create-store.js

BREAKING CHANGE: almin-logger depended on almin 0.13.x
Almin-logger use `context.events.on*` events.
These events is introduced on almin 0.13.x

feat(almin-logger): support almin 0.13.x and transaction

---

packages/almin/src/UILayer/StoreGroup.ts
packages/almin/src/UILayer/StoreGroupEmitChangeChecker.ts
packages/almin/test/Context-test.js
packages/almin/test/Context-transaction-test.js
packages/almin/test/DispatcherPayloadMeta-test.js
packages/almin/test/StoreGroup-edge-case-test.js
packages/almin/test/StoreGroup-test.js
packages/almin/test/UseCaseExecutor-test.js
packages/almin/test/helper/create-new-store.js
packages/almin/test/helper/create-update-store-usecase.js
packages/almin/test/use-case/AsyncUseCase.js
packages/almin/test/use-case/ReturnPromiseUseCase.js
packages/almin/test/use-case/SyncNoDispatchUseCase.js

from #241 
This PR fixes to update on completed payload.
Before:
- When call tryUpdateState on Completed, the useCase is already finished.
After:
- When call tryUpdateState on Completed, the useCase is not finished.
- After tryUpdateState is finished, the useCase is  actually finished.

fix(almin): tryUpdateState should be called before actual finished

---

packages/almin/src/Context.ts
packages/almin/src/UnitOfWork/UnitOfWork.ts
packages/almin/src/UnitOfWork/UseCaseUnitOfWork.ts
packages/almin/src/UseCaseExecutor.ts
packages/almin/src/index.ts
packages/almin/test/Context-test.js
packages/almin/test/UseCaseExecutor-test.js

BREAKING CHANGE: remove on* handler from UseCaseExecutor.
Use UseCaseExecutor#onDispatch instead of it.
We don't know this handler use-case.
If you want to this, please file new issue.
---
- export `UseCaseExecutor` from index
This is useful for wrapper function of `context.useCase`
```js
/**
* Extends React.Component for Container.
* It has executor feature for almin UseCase.
*/
export class BaseContainer<T, P> extends React.Component<T, P> {
useCase<T extends UseCase>(useCase: T): UseCaseExecutor<T> {
return appLocator.context.useCase(useCase);
}
}
```
- https://github.com/azu/faao/blob/master/src/component/container/BaseContainer.ts
fix #206

fix(almin): export UseCaseExecutor from index

---

packages/almin/src/Context.ts
packages/almin/src/UnitOfWork/TransactionContext.ts
packages/almin/src/UnitOfWork/UseCaseUnitOfWork.ts
packages/almin/test/Context-transaction-test.js
packages/almin/test/StoreGroup-test.js

- Add `transactionContext.exit()` for evincive committment
Following case is invalid
```js
await appContext.transaction("bootstrap", async (transactionContext) => {
await transactionContext.useCase(InitializeCustomerUseCase.create()).execute();
// forget to commit!!!
// please commit() or exit()!!!
})
/*
Warning(Transaction): Transaction(${this.name}) should be commit() or exit() at least one. 
If you not want to commit, Please call \`transactionContext.exit()\` at end of transaction.
*/
```
fix #240

fix(almin): add warning to no-commit transaction

---

packages/almin/src/UseCaseExecutor.ts
packages/almin/src/UseCaseExecutorFactory.ts
packages/almin/src/index.ts
packages/almin/test/Context-test.js
packages/almin/test/UseCaseExecutor-test.js
tools/d.ts-markdown.jst
tools/update-api-reference.sh

Export `UseCaseExecutor` interface insteadof `UseCaseExecutorImpl`.
It is more safer for user.
I think that the user can't create new `UseCaseExecutor`.
So, we should not export `UseCaseExecutorImpl`

chore(almin): export interface insteadof UseCaseExecutorImpl

---

docs/tutorial/todomvc/README.md

docs(tutorial): fix a typo

---

docs/tutorial/todomvc/README.md

`Almin life-cycle` link destination was 404, because the target file path was wrong. So I fixed it.

docs(tutorial): fix link

---

docs/tips/performance-profile.md
packages/almin/test/AlminPerfMarker-test.ts

Browser env not support strict...
Fix failure browser test on SauceLabs

test(almin): use deepEqual insteadof deepStrictEqual

---

packages/almin/src/payload/ChangedPayload.ts

almin@0.14.0 deprecated `ChangedPayload`.
refs #281

chore(almin): Deprecate ChangedPayload

---

package.json
packages/almin/package.json
packages/almin/src/Context.ts
packages/almin/src/FunctionalUseCaseContext.ts
packages/almin/src/LifeCycleEventHub.ts
packages/almin/src/UILayer/SingleStoreGroup.ts
packages/almin/src/UILayer/StoreStateMap.ts
packages/almin/src/UseCaseExecutorFactory.ts
packages/almin/src/payload/ChangedPayload.ts
packages/almin/src/payload/CompletedPayload.ts
packages/almin/src/payload/DidExecutedPayload.ts
packages/almin/src/payload/ErrorPayload.ts
packages/almin/src/payload/InitializedPayload.ts
packages/almin/src/payload/Payload.ts
packages/almin/src/payload/StoreChangedPayload.ts
packages/almin/src/payload/TransactionBeganPayload.ts
packages/almin/src/payload/TransactionEndedPayload.ts
packages/almin/src/payload/WillExecutedPayload.ts
packages/almin/test/Dispatcher-test.ts
packages/almin/test/typescript/almin-loading.ts
yarn.lock

BREAKING CHANGE: It have a breaking change in TypeScript.
```js
// OK
class P1 extends Payload{
type = "P1"
}
// OK
class P2 extends Payload {
type: string;
constructor() {
super({ type: "P2" });
}
}
// OK
class P3 extends Payload{
constructor() {
super({ type: "P2" });
}
}
// OK - It is a bug
class P4 extends Payload{
// no type
}
```
If you have inherited `Payload` class, should have defined `type` property.
```js
// OK
class P1 extends Payload{
type = "P1"
}
// OK
class P2 extends Payload {
type: string;
constructor() {
super({ type: "P2" });
}
}
// NG - Need to defined `type: string`
class P3 extends Payload{
constructor() {
super({ type: "P2" });
}
}
// NG: Fix a bug #295 
class P4 extends Payload{
// no type
}
```
fix #295

 fix(almin): Payload subclass need to define "type" property 

---

docs/Components.md

I suppose it's clearer to show an example of Functional UseCase first.
Because the last sentence is 
> It is functional version of UseCase.`
so readers would expect to see a Functional UseCase example at the following line.
Thanks!

docs(UseCase) Change the order of Functional UseCase examples

---

docs/TutorialCounter.md
examples/counter/src/component/App.js
packages/almin-react-container/src/almin-react-container.tsx

React is going to deprecate `componentWillMount` so Almin should use `componentDidMount` instead of `componentWillMount`.
This PR includes fixes for documentation and an example and a source of `almin-react-container`.
Should I separate this PR each one?

fix(React): Use componentDidMount instead of componentWillMount

---

packages/almin-logger/test/AsyncLogger-test.js
packages/almin/src/UseCaseExecutor.ts
packages/almin/test/DispatcherPayloadMeta-test.js
packages/almin/test/UseCaseExecutor-test.ts
packages/almin/test/UseCaseLifeCycle-test.ts
packages/almin/test/mocha.opts
packages/almin/test/use-case/AsyncErrorUseCase.ts

This PR will fix "Failed to execute 'measure' on 'Performance'" error. #310
| UseCase Type         | Will | Did  | Error | Complete | Return Promise                      |
| -------------------- | ---- | ---- | ----- | -------- | ----------------------------------- |
| Sync Success         | 1    | 2    | --    | 3        | resolve(then)                       |
| Async Success        | 1    | 2    | --    | 3        | resolve(then)                       |
| Sync Failure         | 1    | --    | 2     | 3        | reject(catch)                       |
| Async Failure        | 1    | 2    | 3     | 4        | reject(catch)                       |
| ShouldExecute: false | --   | --   | --    | --       | resolve(then) - prevent memory leak |
**Sync Failure**  did not called `didExecute`. …

fix(almin): fix to call didExecute when UseCase throw error

---

packages/almin/src/Context.ts
packages/almin/src/UILayer/StoreGroup.ts
packages/almin/test/LifeCycleEventHub-test.ts
packages/almin/test/StoreGroup-edge-case-test.ts
packages/almin/test/helper/create-new-store.ts
packages/almin/test/helper/create-update-store-usecase.ts

In some case, `LifeCycleEventHub#onDispatch` receive `StoreChangedPayload` #328
This fixes that `StoreChangedPayload` always be `isTrust: true` payload.
`LifeCycleEventHub#onDispatch` ignore trusted Payload.
As a result, LifeCycleEventHub#onDispatch have not received StoreChangedPayload.
fix #328

fix(almin): fix trouble emit `StoreChangedPayload`

---

docs/_ContextAPI.md
docs/_StoreGroupAPI.md
packages/almin/src/Context.ts
packages/almin/test/Context-test.ts
packages/almin/test/helper/create-update-store-usecase.ts

You can write follows in Almin 0.16+
```diff
const context = new Context({
-	dispatcher: new Dispatcher(),
store: storeGroup
});
```
fix #185

feat(almin): Make `dispatcher` optional

---

packages/almin-react-container/src/almin-react-container.tsx

We have used componentDidMount instead of componentWillMount in #321
But, Almin React Container should be initialized before other component.
Because, this component subscribe `Context#onChange`.
In other words, Almin React Container can not handle `Context#onchange` when some store has been changed in Other `Component#componentDidMount`.
Example:
```ts
const AppContainer = AlminReactContainer.create(App, context);
```
App:
```ts
export class App extends BaseContainer<typeof storeGroup.state> {
componentDidMount() {
// this usecase change the storegroup, but App does not re-render.
this.useCase(new ConvertToAnnotationCollectionUseCase()).executor(useCase =>
useCase.execute(fileAnnotationCollections)
);
}
render() {
return <div />
}
}
```
This PR fix this issue.
`Context#onChaneg` should …

fix(react-container): should be initialized before other component

---

package.json
packages/@almin/react-context/package.json
packages/@almin/store-test-helper/package.json
packages/@almin/usecase-bus/package.json
packages/almin-logger/package.json
packages/almin-react-container/package.json
packages/almin/package.json
packages/almin/src/UseCaseExecutor.ts
packages/almin/src/UseCaseExecutorFactory.ts
packages/almin/test/Context-test.ts
packages/almin/type-test/typing-fixtures/execute-argument.ts
yarn.lock

This PR will fix the caveats of #342 
```ts
type Arguments<F extends (...x: any[]) => any> =
F extends (...x: infer A) => any ? A : never;
```
- Require [TypeScript 3.0+](https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/)
Refs #342
fix #107

 fix(almin): make `UseCaseExecutor#execute` type complete

---

packages/@almin/react-context/CHANGELOG.md
packages/@almin/react-context/package.json
packages/@almin/store-test-helper/CHANGELOG.md
packages/@almin/store-test-helper/package.json
packages/@almin/usecase-bus/CHANGELOG.md
packages/@almin/usecase-bus/package.json
packages/almin-logger/CHANGELOG.md
packages/almin-logger/package.json
packages/almin-react-container/CHANGELOG.md
packages/almin-react-container/package.json
packages/almin/CHANGELOG.md
packages/almin/package.json

- **almin:** Drop flow type support
- **almin:** support module field ([#422](https://github.com/almin/almin/issues/422)) ([70ffbb4](https://github.com/almin/almin/commit/70ffbb468f2dfe6d3eb04930867a74e4c56e9431)), closes [#354](https://github.com/almin/almin/issues/354)
- **almin:** drop flow type support ([#427](https://github.com/almin/almin/issues/427)) ([9714b9a](https://github.com/almin/almin/commit/9714b9a65e56bf94c63d1770389ba403f160df73))
- **deps:** update dependency shallow-equal-object to ^1.1.1 ([2734178](https://github.com/almin/almin/commit/2734178e7f53448903e1217d1655a441ec5bcd30))

Almin 0.19.0
