almin/almin

- example/shopping-cart/src/utils/ContextLogger.js
- src/Context.js
make logger async
Reference: https://github.com/fcomb/redux-logger
> feat(logger): improve logger

- README.md
> docs(readme): why creating Almin?

- package.json
- src/UILayer/StoreGroup.js
> chore(browser): add Map polyfill

- .gitignore
- README.md
- SUMMARY.md
- book.json
- docs/README.md
- docs/counter/README.md
- package.json
> feat(docs): setup GitBook

- src/UILayer/StoreGroupValidator.js
- test/StoreGroupValidator-test.js
It is not needed. We have detected same value using WeakMap.
fix #30 minification issue
> fix(storeGroup): remove checking duplicated store name

- .zuul.yml
- package.json
- perf/node-memory-leak-testing/package.json
- perf/node-memory-leak-testing/test.js
- src/UILayer/StoreGroup.js
- test/StoreGroup-test.js
Memory Leak testing for StoreGroup
Before:
Memory usage: 1, 2..3.... MB
After:
Memory usage 1,1,1,1....MB
> perf(test): add memory leak testing

- SUMMARY.md
- book.json
- docs/README.md
- docs/abstract/README.md
Add "Overview: Component of Almin" chapter.
> docs(almin): add abstract chapter to docs

- docs/api/README.md
- src/Store.js
- src/UseCase.js
- test/QueuedStoreGroup-test.js
- test/Store-test.js
Store receive error from UseCase by `Store#onError`.
- Change `Store#onUseCaseError` to `Store#onError`
- `Store#onError` receive `UseCaseErrorPayload` object
close #42
> Breaking Change(Store): Change `Store#onUseCaseError` to `Store#onError`

- package.json
> chore(npm): update to jsdoc-to-assert@4.0.0

- src/UseCase.js
- src/UseCaseContext.js
- src/UseCaseExecutor.js
Add JSDoc to `UseCaseContext` and `UseCaseExecutor`.
refs: https://github.com/almin/almin/pull/59#discussion_r81450242
> docs: add JSDoc for internal class

- package.json
- src/Store.ts
- src/UseCase.ts
- test/Store-test.js
- test/UseCase-test.js
- test/mocha.opts
> fix: support displayName of constructor

- src/Context.ts
- src/UILayer/QueuedStoreGroup.ts
- src/UseCase.ts
- src/UseCaseExecutor.ts
- src/payload/CompletedPayload.ts
- src/payload/DidExecutedPayload.ts
- src/payload/ErrorPayload.ts
- src/payload/WillExecutedPayload.ts
Fix https://github.com/almin/almin/issues/72
> Use a type gurad function to check derived Payload

- src/UseCaseContext.ts
- src/UseCaseExecutor.ts
```diff
- disptcher
+ dispatcher
```
> Fix typo in UseCaseExecutor

- example/todomvc-flow/package.json
- example/todomvc-flow/src/AppLocator.js
- example/todomvc-flow/src/infra/TodoListRepository.js
- example/todomvc-flow/src/usecase/AddTodoItem.js
- package.json
- test/Procfile
I've refactored example tests
- Run `test:example:*`
- Fix flow example project
- Return correct exit status on example tests
> fix(example): fix example tests

- docs/api/README.md
- src/UseCaseContext.ts
- src/UseCaseExecutor.ts
Fix https://github.com/almin/almin/issues/85
> Fix the document of UseCaseContext.constructor

- example/todomvc-flow/package.json
- type-definitions/almin.js.flow
@yamadayuki Can you check it?
close  #93
> feat(flow): Update flow definition

- example/shopping-cart/package.json
- example/svg-feeling/package.json
- example/todomvc-flow/package.json
- example/todomvc/package.json
> Update to Almin and Almin-logger

- example/shopping-cart/package.json
> chore(example): add webpack-dev-server to shopping-cart

- README.md
Fixes grammatical mistakes (that I feel weird) on README.
> Cosme grammar on README

- package.json
- src/UseCaseInstanceMap.ts
> fix(UseCase): add typing to MapLike

- tsconfig.json
> fix(build): fix duplicated source-map

- src/UseCaseContext.ts
- test/UseCaseContext-test.js
- test/use-case/FunctionalUseCase.js
> fix(UseCaseContext): support functional UseCase

- docs/api/Context.md
- docs/api/UseCaseContext.md
- src/Context.ts
- src/StoreLike.ts
fix `Store#onChange: () => {}` return type.
> fix(TypeScript): fix Store#onChange return type

- .github/CONTRIBUTING.md
- README.md
> docs(CONTRIBUTING): Add CONTRIBUTING.md

- test/QueuedStoreGroup-test.js
- test/StoreGroup-test.js
- test/helper/create-store.js
Add `create-store`.
Use it insteadof `EchoeStore`
> refactor(StoreGroup): add create-store

- src/Context.ts
> refactor(Context): change `store` signature to use StoreLike

- src/Store.ts
- src/StoreLike.ts
- src/UILayer/CQRSStoreGroup.ts
> refactore(StoreGorup): separate read and write phase as method

- src/UILayer/CQRSStoreGroup.ts
> fix(StoreGroup): fix immutability check on IE

- package.json
- src/UILayer/CQRSStoreGroup.ts
- src/UILayer/StoreStateMap.ts
> refactor(StoreGroup): use StoreStateMap insteadof inline MapLike

- package.json
- src/Context.ts
- src/FunctionalUseCase.ts
- src/Store.ts
- src/UILayer/StoreGroup.ts
- src/UILayer/StoreGroupValidator.ts
- src/UILayer/StoreStateMap.ts
- tsconfig.json
- Upgradet to TS2.3
- Use  default generic type
- use `strict` option
[Announcing TypeScript 2.3 | TypeScript](https://blogs.msdn.microsoft.com/typescript/2017/04/27/announcing-typescript-2-3/ "Announcing TypeScript 2.3 | TypeScript")
> feat(TypeScript): Upgrade to TypeScript 2.3

- src/UILayer/StoreGroup.ts
- test/StoreGroup-edge-case-test.js
- test/StoreGroup-test.js
> fix(StoreGroup): fix Maximum call stack size exceeded 

- book.json
- docs/tutorial/counter/README.md
- examples/counter/src/component/App.js
- examples/counter/src/store/CounterState.js
- examples/counter/src/store/CounterStore.js
- examples/counter/test/CounterState-test.js
- examples/counter/test/CounterStore-test.js
- package.json
- packages/almin/src/UILayer/StoreGroup.ts
- yarn.lock
- Use StoreGroup
- Fix test cases
- Update Store
> refactor(example): Update Counter example to match latest almin

- perf/benchmark/test/benchmark-test.js
Before: throw erorr
After: Work
> fix(perf): fix benchmark test

- packages/almin/test/DispatcherPayloadMeta-test.js
- perf/benchmark/almin-current.js
- perf/benchmark/package.json
- perf/benchmark/src/measures/increase-store-benchmark/README.md
- perf/benchmark/src/measures/increase-store-benchmark/increse-store.js
- perf/benchmark/yarn.lock
Updating 300 stores = Taken 9ms
> perf(benchmark): add increase-store-benchmark

- examples/shopping-cart/package.json
- examples/shopping-cart/src/components/App.js
- examples/shopping-cart/src/index.js
- examples/shopping-cart/yarn.lock
use `almin-react-container` in an example.
> refactor(example): use almin-react-container in shopping-cart

- .travis.yml
- book.json
- examples/shopping-cart/README.md
- examples/shopping-cart/package.json
- examples/shopping-cart/src/domain/Product/ProductFactory.js
- examples/shopping-cart/src/index.js
- examples/shopping-cart/src/infra/CartRepository.js
- examples/shopping-cart/src/infra/CustomerRepository.js
- examples/shopping-cart/src/infra/ProductRepository.js
- examples/shopping-cart/src/server-index.js
- examples/shopping-cart/src/server/HTML.js
- examples/shopping-cart/src/stores/CartStore/CartStore.js
- examples/shopping-cart/src/stores/CustomerStore/CustomerStore.js
- examples/shopping-cart/src/stores/ProductStore/ProductStore.js
- examples/shopping-cart/src/usecase/Initial/InitializeCustomerUseCase.js
- examples/shopping-cart/src/usecase/Initial/InitializeProductUseCase.js
- examples/shopping-cart/src/usecase/Initial/InitializeRepositoryUseCase.js
- examples/shopping-cart/webpack.config.js
- examples/shopping-cart/yarn.lock
- examples/svg-feeling/test/domain/ColorMixer-test.js
It implement simplified concept of SSR(Server-Side Rendering).
Render `products` data as static html and put it as initial state.
**Client rendering**
**Server-side + Client rendering**
> feat(example): support Server-Side Rendering in shopping cart

- .travis.yml
- package.json
- yarn.lock
> chore(travis): introduce build stage

- .travis.yml
> chore(travis): deploy task without PR

- packages/almin/src/Context.ts
- packages/almin/src/FunctionalUseCaseContext.ts
- packages/almin/src/UseCase.ts
- packages/almin/src/UseCaseContext.ts
> fix(UseCase): make UseCase#execute `abstract`

- .travis.yml
> chore(travis): add guard for deploy pipeline

- packages/almin/src/Context.ts
- packages/almin/src/UILayer/StoreGroup.ts
- packages/almin/src/UnitOfWork/UseCaseUnitOfWork.ts
- packages/almin/src/UseCaseExecutor.ts
- packages/almin/test/StoreGroup-edge-case-test.js
- packages/almin/test/UseCaseExecutor-test.js
- packages/almin/test/typescript/almin-test.ts
- packages/almin/test/use-case/ReturnPromiseUseCase.js
- packages/almin/test/use-case/ThrowUseCase.js
> fix(almin): Do not call duplicated Store#onChange

- docs/tips/nesting-usecase.md
- package.json
> docs(UseCase): Update Nesting UseCase documents

- examples/svg-feeling/yarn.lock
- examples/todomvc-flow/yarn.lock
- examples/todomvc/yarn.lock
- packages/almin/src/Context.ts
- packages/almin/src/UnitOfWork/UseCaseUnitOfWork.ts
- packages/almin/test/Context-test.js
- packages/almin/test/StoreGroup-test.js
- packages/almin/test/UseCaseContext-test.ts
- packages/almin/test/helper/create-new-store.ts
- packages/almin/test/typescript/almin.ts
release event handelr and add test
> test(almin): cleanup && convert UseCaseContext test to TypeScript

- .textlintrc
- .travis.yml
- SUMMARY.md
- docs/introduction/components.md
- docs/introduction/principle.md
- docs/tips/strict-mode.md
- package.json
- packages/almin/src/UILayer/StoreGroupChangingStoreStrictChecker.ts
- packages/almin/test/StoreGroup-test.js
- yarn.lock
add https://almin.js.org/docs/tips/strict-mode.html
> docs(almin): add strict mode docs

- docs/api/Context.md
- docs/api/DispatcherPayloadMeta.md
- docs/api/LifeCycleEventHub.md
- docs/api/Store.md
- docs/api/StoreGroup.md
- docs/api/UseCase.md
- docs/api/UseCaseContext.md
- docs/api/UseCaseExecutor.md
- packages/almin/src/DispatcherPayloadMeta.ts
- packages/almin/src/UseCaseExecutor.ts
> docs(almin): Update API reference

- docs/tips/strict-mode.md
- packages/almin/src/UILayer/StoreGroupChangingStoreStrictChecker.ts
> docs(almin): improve strict mode warning

- docs/api/LifeCycleEventHub.md
- docs/api/Store.md
- packages/almin/src/Dispatcher.ts
- packages/almin/src/LifeCycleEventHub.ts
- packages/almin/src/Store.ts
- packages/almin/src/UILayer/StoreGroup.ts
- packages/almin/test/Context-transaction-test.ts
- packages/almin/test/UseCaseUnitOfWork-test.js
BREAKING CHANGE: Store#onDispatch receive only your events
It is difference with Store#receivePayload.
fix #254
> fix(Store): Store#onDispatch receive only dispatched the Payload by UseCase#dispatch

- package.json
- packages/almin/src/Context.ts
- packages/almin/src/UnitOfWork/TransactionContext.ts
- packages/almin/src/UnitOfWork/UnitOfWork.ts
- packages/almin/src/UnitOfWork/UnitOfWorkIdGenerator.ts
- packages/almin/src/UnitOfWork/UseCaseUnitOfWork.ts
- packages/almin/test/Context-transaction-test.ts
- packages/almin/test/UnitOfWork-test.js
> feat(almin): Add UnitOfWork#id property

- .eslintrc.json
- docs/tutorial/counter/README.md
- examples/counter/src/component/App.js
- examples/counter/src/component/Counter.js
- examples/counter/src/index.js
- examples/counter/src/store/CounterState.js
- examples/counter/src/store/CounterStore.js
- examples/counter/src/usecase/IncrementalCounterUseCase.js
- examples/counter/test/CounterState-test.js
- examples/counter/test/CounterStore-test.js
- examples/counter/test/IncrementalCounterUseCase-test.js
- Enable strict
- Separate index and App
> refactor(example): Update Counter example

- packages/almin/src/DispatcherPayloadMeta.ts
- packages/almin/src/UnitOfWork/UseCaseUnitOfWork.ts
- packages/almin/test/Context-transaction-test.ts
> feat(almin): support TransactionContext#id and meta.transaction.id

- packages/almin/src/Context.ts
- packages/almin/test/Context-test.js
> chore(almin): add actual deprecated warning to API

- .travis.yml
- packages/almin-logger/examples/package.json
- perf/node-memory-leak-testing/package.json
> chore(ci): reduce CI time

- .travis.yml
> perf(travis): use if: condition

- packages/almin/src/payload/Payload.ts
> fix(almin): Make Payload abstract class

- packages/almin/package.json
- packages/almin/yarn.lock
Add [size-limit](https://github.com/ai/size-limit "size-limit"): 15kb.
Result: 
```
$ npm-run-all -s clean build
$ size-limit
Package size: 12.49 KB
Size limit:   15 KB
With all dependencies, minified and gzipped
```
> test(almin): add size-limit testing

- README.md
> docs(almin): fix link

- docs/tips/usecase-lifecycle.md
- packages/almin-logger/src/AsyncLogger.ts
- packages/almin-logger/test/AsyncLogger-test.js
- packages/almin-logger/test/usecase/NotExecuteUseCase.js
- packages/almin/src/LifeCycleEventHub.ts
- packages/almin/src/UseCase.ts
- packages/almin/src/UseCaseExecutor.ts
- packages/almin/src/UseCaseLike.ts
- packages/almin/src/index.ts
- packages/almin/src/payload/WillNotExecutedPayload.ts
- packages/almin/test/Context-test.js
- packages/almin/test/UseCase-test.js
- packages/almin/test/UseCaseExecutor-test.js
- packages/almin/test/use-case/NotExecuteUseCase.js
Allow the user to implment `UseCase#shouldExecute(): boolean`.
fix #292
> feat(almin): Support UseCase#shouldExecute

- examples/todomvc-typescript/yarn.lock
- perf/benchmark/almin-0.13.js
- perf/benchmark/almin-0.14.js
- perf/benchmark/index.js
- perf/benchmark/pacakges/almin-0.13/index.js
- perf/benchmark/pacakges/almin-0.13/package.json
- perf/benchmark/pacakges/almin-0.14/index.js
- perf/benchmark/pacakges/almin-0.14/package.json
- perf/benchmark/package.json
- perf/benchmark/src/lots-of-stores-task.js
- perf/benchmark/src/measures/increase-store-benchmark/increse-store.js
- perf/benchmark/src/task.js
- perf/benchmark/yarn.lock
Update target
- 0.13
- 0.14
- current
> fix(perf): fix Benchmark script

- .textlintrc
- docs/Components.md
- docs/GuidePerformancProfile.md
- docs/GuideUsecaseLifecycle.md
- docs/TutorialTodoApp.md
- docs/_ContextAPI.md
- docs/_LifeCycleEventHubAPI.md
- docs/_StoreAPI.md
- docs/_UseCaseAPI.md
- package.json
- packages/almin/src/Context.ts
- packages/almin/src/LifeCycleEventHub.ts
- packages/almin/src/Store.ts
- packages/almin/src/UILayer/StoreGroupChangingStoreStrictChecker.ts
- packages/almin/src/UseCase.ts
- website/pages/en/index.js
- yarn.lock
[textlint-rule-no-dead-link](https://github.com/textlint-rule/textlint-rule-no-dead-link-fork) found issues.
fix #306
>  fix(docs): fix documentation links 

- website/siteConfig.js
https://community.algolia.com/docsearch/documentation/
https://github.com/algolia/docsearch-configs/blob/master/configs/almin_js.json
> feat(website): add DocSearch integration

- packages/almin/src/payload/ChangedPayload.ts
- packages/almin/src/payload/CompletedPayload.ts
- packages/almin/src/payload/DidExecutedPayload.ts
- packages/almin/src/payload/ErrorPayload.ts
- packages/almin/src/payload/InitializedPayload.ts
- packages/almin/src/payload/StoreChangedPayload.ts
- packages/almin/src/payload/TransactionBeganPayload.ts
- packages/almin/src/payload/TransactionEndedPayload.ts
- packages/almin/src/payload/WillExecutedPayload.ts
- packages/almin/src/payload/WillNotExecutedPayload.ts
Feedback from https://twitter.com/kinjou__j/status/948859338445045761
> refactor(almin): format Payload type

- docs/Principles.md
Currently, the image is 404.
https://almin.js.org/docs/en/principles.html
Is the image https://github.com/almin/almin/blob/master/docs/assets/almin-unit-of-work.png ?
> docs(Principles): Fix an image path of Unit of work

- docs/Components.md
- docs/GettingStarted.md
- docs/HelloWorld.md
- docs/Principles.md
- website/pages/en/index.js
Thank you for great documentation! I really enjoy to read it.
This is a PR to fix some words which I've found it through reading the Introduction section.
> docs(Introduction): Fix some words in Introduction

- docs/ExampleProjects.md
- docs/TutorialCounter.md
- docs/TutorialTodoApp.md
This PR is a follow up for #319 📝
> docs(Tutorial): Refactor tutorial documentations

- .github/CONTRIBUTING.md
From https://github.com/almin/almin/pull/321#issuecomment-358956412
> docs(CONTRIBUTING): update commit message style

- packages/almin/src/Context.ts
- packages/almin/src/FunctionalUseCaseContext.ts
- packages/almin/src/UILayer/StoreGroup.ts
- packages/almin/test/StoreGroup-test.ts
- packages/almin/test/helper/create-new-store.ts
- yarn.lock
> test(almin): Convert StoreGroup-test to TypeScript

- .textlintrc
- docs/GuideTypeScript.md
- package.json
- website/sidebars.json
- yarn.lock
> docs(TypeScript): add TypeScript document

- packages/almin-logger/package.json
- website/blog/2018-06-09-almin-0.17.md
- website/siteConfig.js
>  feat(blog): 2018-06-09-almin-0.17.md 

- packages/@almin/react-context/CHANGELOG.md
- packages/@almin/react-context/package.json
- packages/@almin/store-test-helper/CHANGELOG.md
- packages/@almin/store-test-helper/package.json
- packages/@almin/usecase-bus/CHANGELOG.md
- packages/@almin/usecase-bus/package.json
- packages/almin-logger/CHANGELOG.md
- packages/almin-logger/package.json
- packages/almin-react-container/CHANGELOG.md
- packages/almin-react-container/package.json
- packages/almin/CHANGELOG.md
- packages/almin/package.json
fix warning message
- almin-logger@6.2.3
- almin-react-container@0.7.3
- almin@0.18.1
- @almin/react-context@1.1.3
- @almin/store-test-helper@1.1.3
- @almin/usecase-bus@1.2.2
> Publish almin@0.18.1

- examples/todomvc-typescript/src/components/TodoApp.react.tsx
- package.json
- packages/almin-react-container/test/almin-react-container-test.tsx
- packages/almin/package.json
- yarn.lock
Upgrade to size-limit@2
https://github.com/ai/size-limit/blob/master/CHANGELOG.md
> chore(deps): update size-limit@2

- docs/Principles.md
- examples/counter/README.md
- examples/todomvc-flow/README.md
- examples/todomvc-typescript/README.md
- examples/todomvc/README.md
* Fix some broken links in the doc.
* https://github.com/perf/benchmarks/issues is also broken, but I couldn't see where it'd gone, so I leave it as it was.
> Fix broken links in the doc

- .gitignore
- packages/almin/package.json
- packages/almin/tsconfig.module.json
I tried the module field support of "almin package" with reference to [this article](https://dwango-js.github.io/performance-handbook/startup/module-field/).
Please review my changes.
fix #354
> feat(almin): support module field
